export const clients = [
    "RASHMI METALIKS LIMITED",
    "SHAKAMBHARI ISPAT LTD",
    "SUPER SMELTERS LIMITED",
    "RASHMI CEMENT LIMITED",
    "BHUSHAN POWER & STEEL",
    "JINDAL STEEL",
    "TATA STEEL",
    "JSW STEEL",
    "SAIL",
    "ACC CEMENT",
    "ULTRATECH CEMENT",
    "AMBUJA CEMENT",
];