export const clients = [
    "RASHMI METALIKS LIMITED",
    "SHAKAMBHARI ISPAT LTD",
    "SUPER SMELTERS LIMITED",
    "RASHMI CEMENT LIMITED",

    // Added Clients
    "LARSEN & TOUBRO (L&T)",
    "AFCONS INFRASTRUCTURE LIMITED",
    "ASHOKA BUILDCON LIMITED",
    "SHYAM STEEL INDUSTRIES LIMITED",
    "GALLANT ISPAT LIMITED",
    "TARANJOT RESOURCES PRIVATE LIMITED",

    "TATA STEEL",
    "JSW STEEL",
    "SAIL",
    "ACC CEMENT",
    "ULTRATECH CEMENT",
    "AMBUJA CEMENT",


];